language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --no-dev
  - curl -LSs https://box-project.github.io/box2/installer.php | php

script:
  - phpunit
  - php box.phar build; rm -rf vendor; php spress.phar --version

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0957171278778ab21da9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
